name = "my-dads-soft-recovery"
type = "javascript"

[build]
command = "npm install"

kv_namespaces = [
  { binding = "ORDERS", id = "xxxxxxx", preview_id = "xxxxxxx" }
]

[env.production]
name = "my-dads-soft-recovery-worker"
